#!/bin/bash
a="http://192.168.255.128/acrn/1.patch,http://192.168.255.128/acrn/2.patch"
#要将$a分割开，可以这样：
OLD_IFS="$IFS"
IFS=","
arr=($a)
IFS="$OLD_IFS"
for s in ${arr[@]}
do
    echo "$s"
    OLD_IFS="$IFS"
    IFS="/"
    arr2=($s)
    IFS="$OLD_IFS"
    echo ${arr2[-1]}
done
